################################################################
#                            _                                 #
#                         _ooOoo_                              #
#                        o8888888o                             #
#                        88" . "88                             #
#                        (| -_- |)                             #
#                        O\  =  /O                             #
#                     ____/`---'\____                          #
#                   .'  \\|     |//  `.                        #
#                  /  \\|||  :  |||//  \                       #
#                 /  _||||| -:- |||||_  \                      #
#                 |   | \\\  -  /'| |   |                      #
#                 | \_|  `\`---'//  |_/ |                      #
#                 \  .-\__ `-. -'__/-.  /                      #
#               ___`. .'  /--.--\  `. .'___                    #
#            ."" '<  `.___\_<|>_/___.' _> \"".                 #
#           | | :  `- \`. ;`. _/; .'/ /  .' ; |                #
#           \  \ `-.   \_\_`. _.'_/_/  -' _.' /                #
# ===========`-.`___`-.__\ \___  /__.-'_.'_.-'================ #
#                         `=--=-'                              #
#                                                              #
#  No Bug - No Error - No Warning - Smooth Build - No Bootloop #
#                                                              #
################################################################

env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_conf: "ENCRYPTED[824585a540c34cec760aa624121ffe747b3fb26f912bee6b8441950de5f824c47becf40e034088ef3e4ec606245ea684]"

task:
  name: master
  timeout_in: 2h
  only_if: $CIRRUS_REPO_OWNER == 'Doraemon-Kernel'
  container:
    image: dopaemon/bionic:latest
    cpu: 4
    memory: 6G

  Install_Packages_Ubuntu_script:
    - cd /tmp/ci/
    - rm -rf *
    - sudo apt-get update
    - sudo apt-get install -y ccache rclone git-lfs bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
  Git_Clone_From_Github_script:
    - cd /tmp/ci/
    - echo "git clone -b gcc --depth="1" https://github.com/Doraemon-Kernel/arm-linux-androideabi-4.9.git" >> /dev/null
    - echo "git clone -b gcc --depth="1" https://github.com/Doraemon-Kernel/aarch64-linux-android-4.9.git" >> /dev/null
    - git clone -b master --depth="1" https://github.com/kdrag0n/proton-clang.git clang
    - git clone -b eleven --depth="1" https://github.com/Doraemon-Kernel/android_kernel_xiaomi_sweet.git kernel
  Rclone_Configure_script:
    - mkdir -p ~/.config/rclone
    - echo "$rclone_conf" > ~/.config/rclone/rclone.conf
  Compile_Kernel_script:
    - cd /tmp/ci/kernel
    - export PATH="/tmp/ci/clang/bin:$PATH"
    - export ARCH=arm64
    - export SUBARCH=arm64
    - echo "export DTC_EXT=dtc" >> /dev/null
    - echo "export CROSS_COMPILE=/tmp/ci/aarch64-linux-android-4.9/bin/aarch64-linux-android-" >> /dev/null
    - echo "export CROSS_COMPILE_ARM32=/tmp/ci/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-" >> /dev/null
    - export CROSS_COMPILE=aarch64-linux-gnu-
    - export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
    - make O=out sweet-perf_defconfig ARCH=arm64
    - make -j$(nproc --all) O=out ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu-
  Check_Directory_script:
    - cd /tmp/ci/kernel
    - ls out/arch/arm64/boot
  Compile_Flashable_script:
    - cd /tmp/ci/kernel
    - mv out/arch/arm64/boot/dtbo.img Doraemon/Flashable/
    - mv out/arch/arm64/boot/Image.gz-dtb Doraemon/Flashable/
    - cd Doraemon/Flashable/
    - zip -rv9 Doraemon-Kernel-Sweet-AOSP-R1.0-Beta.zip Image.gz-dtb META-INF anykernel.sh dtbo.img tools
  Upload_Flashable_script:
    - cd /tmp/ci/kernel/Doraemon/Flashable/
    - rclone copy -v Doraemon-Kernel-Sweet-AOSP-R1.0-Beta.zip drive:Share/Devices/Sweet/Doraemon-Kernel/AOSP/
